version : '3.8'

services:  
  postgre-db:
    container_name: 'postgre-db'
    image: postgres
    environment:
      - POSTGRES_USER=SetUpUser
      - POSTGRES_PASSWORD=SetUpPassword
    ports:
      - 5432:5432
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    external: true 