version: '3.8'

services:
  mongo-db:
    container_name: 'mongo-db'
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db
    networks:
      - app

networks:
  app:
    external: true