version: '3.8'

services:
  mongo-admin:
    container_name: 'mongo-admin'
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    restart: always
    ports:
      - 8081:8081
    networks:
      - app

networks:
  app:
    external: true